Add document about AWS deployment and upgrades
open-craft/openedx-deployment pull request #12
Opened 2017-09-14 21:50 UTC by clemente

**Testing instructions**
- [ ] check that nothing important is missing
- [ ] check that it's true
- [ ] check formatting

**Reviewers**
- [ ] @pomegranited

2017-09-15 06:52 UTC, pomegranited requested changes
@clemente  Good start for these docs, thank you.

Will approve once my comments have been addressed.

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +
The audience for this documentation repository is the public, and so they don't necessarily know about OCIM.  Please remove these references, and update this intro to suit an AWS-only universe.

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +- At the end of the deployment process, we switch an IP to point to the final instance; in Amazon it's called [Elastic IP](../shared/Elastic_IP.md)
The activation mechanism will differ for everyone; some use ElasticIP, some use load balancers, some direct DNS.

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +1. create a new instance
nit: "EC2 instance".

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +1. run `ansible-playbook` from [director](../shared/director.md)
... using the [configuration/playbook/edx_sandbox.yml](https://github.com/edx/configuration/blob/master/playbooks/edx_sandbox.yml), with the `aws` role added.

Provide an example command here.

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +Note that we don't upgrade any program in the old instance, nor do we stop programs. The deployment happens in a new instance and later we switch to it. For a short time, both instances could be acce
nit: "program" doesn't make sense here.. could you say instead "Note that we don't modify the old instance, or stop any services running there."

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +- [Lumerical, Sept 2017: Ficus.3 to Ficus.4 and then to Ginkgo.1](https://docs.google.com/document/d/1R4_gm1WjwDCpNAddDOBaFEaKM4QO-78jFucap7ul6OA/edit#heading=h.4bpi03oynxtd)
Hmm.. I know why you're linking to this document, but it's not really ready for public consumption.  Could you please remove this link, and we'll just use it internally?

2017-09-15 06:52 UTC, pomegranited commented on docs/openstack-openedx/production-deployment.md
> +To deploy to Amazon Web Services, see [AWS deployment](../aws-openedx/aws-deployment.md).
Please remove this statement -- this document is specifically about "supported" production deployments, which are currently only OpenStack.

2017-09-15 06:52 UTC, pomegranited commented on docs/shared/director.md
> +A new openedx release can include a newer version of `ansible`. Because ansible playbooks are to be run from `director`, we musto update the packages in `director`'s virtualenv. To do so:
nit: ...`ansible` or other python packages.

2017-09-15 06:52 UTC, pomegranited commented on docs/shared/director.md
> +A new openedx release can include a newer version of `ansible`. Because ansible playbooks are to be run from `director`, we musto update the packages in `director`'s virtualenv. To do so:
typo: "musto" should be "must"

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +1. set up `vars.yml` in `edx-configuration`
1. It doesn't matter where vars.yml lives; its path is set when calling by the `ansible-playbook` command.
1. Note that the variables in this file override the defaults provided by [edx:configuration](https://github.com/edx/configuration)
1. Secure information, e.g. secret keys and OAuth keys, should be kept safe and private.

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +1. wait
... for provisioning to complete.

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +1. run `ansible-playbook` from [director](../shared/director.md)
"Provision the new server by running..."

2017-09-15 06:52 UTC, pomegranited commented on docs/aws-openedx/aws-deployment.md
> +1. test
... the new service.

2017-09-15 20:59 UTC, clemente commented
@pomegranited  I applied your comments

2017-09-18 10:58 UTC, pomegranited commented
Thanks @clemente, your changes look fine :+1:

- [x] <strike>I tested this</strike> - just read through it.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation

2017-09-18 10:58 UTC, pomegranited approved these changes

2017-09-18 17:09 UTC, merged