Add draft of supported deployment plans (OC-2166)
open-craft/openedx-deployment pull request #6
Opened 2017-06-07 17:53 UTC by bradenmacdonald

@antoviaque Can you please review, merge, and deploy this? (Or will it automatically deploy if I merge it?)

This is a Markdown version of the Google doc seen by you and Ned already, with the language changed in a couple places to indicate that this is a proposal and we are wanting to see if there's community interest before we move forward.

Once this is deployed, I'll post on the ML and Slack, and we'll see what interest there is.

2017-06-08 16:45 UTC, antoviaque requested changes
@bradenmacdonald Did a pass on this, a few remaining comments, but nothing major.

2017-06-08 16:45 UTC, antoviaque commented on docs/openstack-openedx/supported-deployment.md
> +edX does not officially provide any supported method for deploying a production-grade instance of Open edX. However, the following *proposed* method for setting up a production-grade instance on Open
Can we not promise the support for this? As mentioned in the past I'd rather under promise, and over deliver.

2017-06-08 16:45 UTC, antoviaque commented on docs/openstack-openedx/supported-deployment.md
> +## How to deploy for the first time
These instructions had been tested during the initial review, right?

2017-06-08 16:45 UTC, antoviaque commented on docs/openstack-openedx/supported-deployment.md
> +1. In that new repository, create a vars.yml file using [this template](https://github.com/open-craft/opencraft/pull/204) (or [this alternate template](https://github.com/open-craft/openedx-deploymen
Can we only mention the first one, since we wouldn't want to maintain the second one?

2017-06-08 16:45 UTC, antoviaque commented on docs/openstack-openedx/supported-deployment.md
> +1. Set up a "director" VM following [these instructions](http://opencraft.com/doc/openedx-deployment/shared/director/).
If this link is in the same document set, it can be a relative link here no?

2017-06-09 22:30 UTC, bradenmacdonald commented on docs/openstack-openedx/supported-deployment.md
> +## How to deploy for the first time
No. As you can see, it's a ton of work to go through this, so I wanted to gauge interest first. Testing this thoroughly would probably take 1-2 days?

I did test a very similar process on a recent client setup, but I haven't tested these specific instructions, and there is no doubt some minor issues with it that will need to be fixed.

2017-06-12 09:35 UTC, antoviaque commented on docs/openstack-openedx/supported-deployment.md
> +## How to deploy for the first time
@bradenmacdonald In that case, when you announce it, present it as an alpha release, saying that we are both trying to jauge interest, and looking for people to help us test it. This way, that would make it clear that we don't expect this to work flawlessly.

2017-06-12 09:36 UTC, antoviaque approved these changes

2017-06-12 09:37 UTC, merged

2017-06-12 09:45 UTC, antoviaque commented on docs/openstack-openedx/supported-deployment.md
> +## How to get support (Proposal - this is not yet actively supported)
@bradenmacdonald I merged and deployed: http://opencraft.com/doc/openedx-deployment/

But reading it again there, I've noticed there are still mentions of supporting it, so I'm removing them, see https://github.com/open-craft/openedx-deployment/commit/5a8e64dbfd98abb2a00f2cd170f48e72d5981df4

2017-06-12 18:07 UTC, bradenmacdonald commented on docs/openstack-openedx/supported-deployment.md
> +## How to get support (Proposal - this is not yet actively supported)
@antoviaque Thanks!